# NumPy 

#       **Creating a Numpy Array**

In [32]:
import numpy as np

In [33]:
#To check version
print(np.__version__)

1.20.3


In [34]:
#0D array
arr = np.array(12)
print(arr)

12


In [35]:
#1D array
arr = np.array([1, 2, 3, 4])
print("Rank 1 Array: \n",arr)

#Type of array
print(type(arr))

Rank 1 Array: 
 [1 2 3 4]
<class 'numpy.ndarray'>


In [36]:
#2D Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Rank 2 Array: \n", arr)

Rank 2 Array: 
 [[1 2 3]
 [4 5 6]]


In [37]:
#3D Array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [38]:
# Use a tuple to create a NumPy array:
arr = np.array((1, 2, 3, 4))
print("\nArray created using tuple:\n", arr)


Array created using tuple:
 [1 2 3 4]


In [39]:
#Check Number of Dimensions

a = np.array(20)
b = np.array([1, 2, 3, 4])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])


In [40]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3
