# NumPy 

#       **Creating a Numpy Array**

In [1]:
import numpy as np

In [2]:
#To check version
print(np.__version__)

1.20.3


In [3]:
#0D array
arr = np.array(12)
print(arr)

12


In [4]:
#1D array
arr = np.array([1, 2, 3, 4])
print("Rank 1 Array: \n",arr)

#Type of array
print(type(arr))

Rank 1 Array: 
 [1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
#2D Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Rank 2 Array: \n", arr)

Rank 2 Array: 
 [[1 2 3]
 [4 5 6]]


In [6]:
#3D Array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
# Use a tuple to create a NumPy array:
arr = np.array((1, 2, 3, 4))
print("\nArray created using tuple:\n", arr)


Array created using tuple:
 [1 2 3 4]


In [8]:
#Check Number of Dimensions

a = np.array(20)
b = np.array([1, 2, 3, 4])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])


In [9]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [10]:
zero = np.zeros((2,5))

In [11]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
rng = np.arange(15)

In [13]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
rng.shape

(15,)

In [15]:
rng.dtype

dtype('int32')

In [16]:
arr = np.arange(0,21,5)

In [17]:
arr

array([ 0,  5, 10, 15, 20])

In [18]:
lspace = np.linspace(0,100,10)

In [19]:
lspace

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [20]:
# To create empty array 
emp= np.empty((1,5))

In [21]:
emp

array([[0., 0., 0., 0., 0.]])

In [22]:
# To create epmty arrya simmilar shape of previously created array
emp_like= np.empty_like(lspace)

In [23]:
emp_like

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [24]:
# To create identical array
ide = np.identity((10))

In [25]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
ide.shape

(10, 10)

In [27]:
arr = np.empty((3,10))

In [28]:
arr

array([[6.75026322e-312, 6.75026474e-312, 0.00000000e+000,
        0.00000000e+000, 4.17340416e-306, 5.02034658e+175,
        9.20378503e+169, 2.21334108e+160, 3.92650443e-033,
        1.34683964e+165],
       [2.59027860e-144, 3.80985069e+180, 1.14428494e+243,
        2.59027907e-144, 7.79952704e-143, 1.42423664e+160,
        2.57543226e-056, 2.00416439e-052, 1.10610206e+165,
        4.99874558e+217],
       [5.49419094e-143, 2.91237123e+257, 5.56111702e+180,
        5.74015544e+180, 1.94919988e-153, 2.59027858e-144,
        2.59903818e-144, 5.27365186e-091, 1.83323181e-076,
        1.24502515e-047]])

In [29]:
# ravel convert the all ndim array into 1d arry
arr = arr.ravel() 
arr

array([6.75026322e-312, 6.75026474e-312, 0.00000000e+000, 0.00000000e+000,
       4.17340416e-306, 5.02034658e+175, 9.20378503e+169, 2.21334108e+160,
       3.92650443e-033, 1.34683964e+165, 2.59027860e-144, 3.80985069e+180,
       1.14428494e+243, 2.59027907e-144, 7.79952704e-143, 1.42423664e+160,
       2.57543226e-056, 2.00416439e-052, 1.10610206e+165, 4.99874558e+217,
       5.49419094e-143, 2.91237123e+257, 5.56111702e+180, 5.74015544e+180,
       1.94919988e-153, 2.59027858e-144, 2.59903818e-144, 5.27365186e-091,
       1.83323181e-076, 1.24502515e-047])

In [30]:
arr.shape

(30,)

In [31]:
#This gives all consumed size of the given array
arr.nbytes

240

In [32]:
arr.ndim

1

In [37]:
#Reshape the array
arr.reshape(2,15)

array([[6.75026322e-312, 6.75026474e-312, 0.00000000e+000,
        0.00000000e+000, 4.17340416e-306, 5.02034658e+175,
        9.20378503e+169, 2.21334108e+160, 3.92650443e-033,
        1.34683964e+165, 2.59027860e-144, 3.80985069e+180,
        1.14428494e+243, 2.59027907e-144, 7.79952704e-143],
       [1.42423664e+160, 2.57543226e-056, 2.00416439e-052,
        1.10610206e+165, 4.99874558e+217, 5.49419094e-143,
        2.91237123e+257, 5.56111702e+180, 5.74015544e+180,
        1.94919988e-153, 2.59027858e-144, 2.59903818e-144,
        5.27365186e-091, 1.83323181e-076, 1.24502515e-047]])