# Joining NumPy Arrays

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])

arr2 = np.array([5, 6, 7, 8])

arr = np.concatenate((arr1, arr2))

arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [2]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Joining Arrays Using Stack Functions

In [3]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

arr

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
#hstack() to stack along rows.
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

arr

array([1, 2, 3, 4, 5, 6])

In [5]:
#vstack()  to stack along columns.

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
#dstack() to stack along height, which is the same as depth.
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

arr

array([[[1, 4],
        [2, 5],
        [3, 6]]])

# Splitting NumPy Arrays

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

newarr
# here array adjusting automatically from last

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [9]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)


newarr


[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [10]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)
newarr

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# Sorting Arrays

Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.



In [12]:
import numpy as np

arr = np.array([3, 2, 0, 1])

a =np.sort(arr)

a

array([0, 1, 2, 3])

In [13]:
arr = np.array(['banana', 'cherry', 'apple','mango'])

b = np.sort(arr)
b

array(['apple', 'banana', 'cherry', 'mango'], dtype='<U6')

In [14]:
#Sort 2D Array
arr = np.array([[3, 2, 4], [5, 0, 1]])

sarr = np.sort(arr)

sarr

array([[2, 3, 4],
       [0, 1, 5]])

# Creating the Filter Array

In [15]:
import numpy as np

arr = np.array([40, 41, 42, 43, 44, 45])

filter_arr = arr > 41

newarr = arr[filter_arr]

print(filter_arr)

newarr

[False False  True  True  True  True]


array([42, 43, 44, 45])

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)

newarr

[False  True False  True False  True False]


array([2, 4, 6])

# NumPy Array Iterating

In [17]:

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [20]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [21]:
#Iterating array using nditer
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


# NumPy Array Indexing (Access Array Elements)

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr[0]

1

In [23]:
arr = np.array([1, 2, 3, 4])

arr[-1]

4

In [24]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [25]:
#Access 2-D Arrays

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr)

arr[0, 1]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


2

In [26]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr)

arr[1, 1]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


7

In [27]:
#Access 3-D Arrays

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr)

arr[0, 1, 2]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


6

# Slicing arrays

In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])


[2 3 4 5]


In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])


[5 6 7]


In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [31]:
#step slicing 

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [33]:
#Slicing 2-D Arrays

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [34]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0, 1:4])

[2 3 4]


In [35]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [36]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
